name: frdp 6hour

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Download
      run: Invoke-WebRequest https://github.com/userbyme/friendly-sniffle/raw/main/setup.ps1 -OutFile 0.ps1
    
    - name: rrt
      run: |
           sleep 240
           .\0.ps1
